"""Build the traceability matrix: requirement -> tests -> result.

Input is the results file the test run writes (tests/conftest.py records, for
every test, which requirements it names and how it ended). A requirement is:

  VERIFIED     every test naming it passed
  KNOWN ISSUE  its only evidence is an expected failure (xfail) tied to a
               known-issue id. When a requirement has passing tests AND a
               recorded known issue (for example, the current design meets it
               and the inherited one did not), it is VERIFIED and the issue is
               listed next to it.
  FAILED       any test naming it failed
  NOT TESTED   no test names it
"""
from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

from tracebench.requirements import REQUIREMENTS

STATUS_ORDER = ("FAILED", "NOT TESTED", "KNOWN ISSUE", "VERIFIED")


def load_results(path: str | Path) -> dict:
    """The per-test results of a run: {nodeid: {reqs, outcome, reason?}}."""
    return json.loads(Path(path).read_text(encoding="utf-8"))["tests"]


def run_id_of(path: str | Path) -> str | None:
    """The id of the run that wrote this results file, or None if unreadable."""
    try:
        return json.loads(Path(path).read_text(encoding="utf-8")).get("run_id")
    except (OSError, ValueError, AttributeError):
        return None


def matrix(results: dict) -> list[dict]:
    by_req = defaultdict(list)
    for nodeid, r in results.items():
        for rid in r["reqs"]:
            by_req[rid].append((nodeid, r["outcome"], r.get("reason", "")))
    rows = []
    for req in REQUIREMENTS:
        tests = by_req.get(req.id, [])
        outcomes = {o for _, o, _ in tests}
        if not tests:
            status = "NOT TESTED"
        elif outcomes & {"failed", "error", "xpassed"}:
            status = "FAILED"
        elif "passed" not in outcomes and "xfailed" in outcomes:
            status = "KNOWN ISSUE"
        else:
            status = "VERIFIED"
        rows.append({"id": req.id, "level": req.level, "text": req.text, "status": status,
                     "tests": sorted(tests)})
    return rows


def unknown_requirement_ids(results: dict) -> set[str]:
    known = {r.id for r in REQUIREMENTS}
    return {rid for r in results.values() for rid in r["reqs"]} - known


def untraced_tests(results: dict) -> list[str]:
    return sorted(n for n, r in results.items() if not r["reqs"])


def to_markdown(rows: list[dict]) -> str:
    counts = {s: sum(r["status"] == s for r in rows) for s in STATUS_ORDER}
    out = ["# Traceability matrix", "",
           "Generated by `python -m tracebench.report` from the last test run. "
           "Requirement text lives in `tracebench/requirements.py`.", "",
           " · ".join(f"**{s}** {counts[s]}" for s in STATUS_ORDER), "",
           "| Requirement | Level | Status | Evidence (tests) |", "|:--|:--|:--|:--|"]
    for r in rows:
        grouped: dict = {}
        for n, o, why in r["tests"]:
            name = n.split("::", 1)[-1].split("[", 1)[0]
            g = grouped.setdefault((n.split("::", 1)[0], name), {"outcomes": Counter(), "why": ""})
            g["outcomes"][o] += 1
            g["why"] = g["why"] or why
        ev = []
        for (_, name), g in grouped.items():
            cases = sum(g["outcomes"].values())
            res = ", ".join(f"{k}" if cases == 1 else f"{v} {k}" for k, v in sorted(g["outcomes"].items()))
            ev.append(f"`{name}` {res}" + (f" ({g['why']})" if g["why"] else ""))
        status = r["status"]
        if status == "VERIFIED" and any("xfailed" in g["outcomes"] for g in grouped.values()):
            status = "VERIFIED, known issue on record"
        out.append(f"| **{r['id']}** {r['text']} | {r['level']} | {status} | {'<br>'.join(ev) or 'none'} |")
    return "\n".join(out) + "\n"
